$
$ THIS FILES IS GENERATED/UPDATED AUTOMATICALLY
$
$ See gencat(1) for more information about its format.
$
$quote "
$set 1 DELTA_FREQ_C_SET
$ delta_freq.c: line 81
$ MD5 ("Invalid frequency") = 6a9f023a4a482e24e4b3753435db773e
81 "Invalid frequency"
$set 2 HELP_C_SET
$ help.c: line 45
$ MD5 ("Available commands") = 4d026fa0328ba77fbe5ec119d7d94d97
45 "Available commands"
$ help.c: line 68
$ MD5 ("The word \"set\" is not required.") = 182ef675aa34edcd208999742c616ac9
68 "The word \"set\" is not required."
$ help.c: line 69
$ MD5 ("It is possible to specify only the") = 34f09513373263f0edf1d769efe44938
69 "It is possible to specify only the"
$ help.c: line 70
$ MD5 ("frequency.") = 092edcff70a85b601b83009fb34fed39
70 "frequency."
$set 3 MAIN_C_SET
$ main.c: line 107
$ MD5 ("USB Radio Control utility,") = 879cb79ea281f0e716a65c3d6539427b
107 "USB Radio Control utility,"
$ main.c: line 108
$ MD5 ("version") = 5528902f5bba56c686370cd5d6a1399e
108 "version"
$ main.c: line 120
$ MD5 ("no UFM device specified, using") = d80cd1a293b8bcc5b3b314b62c9c85d9
120 "no UFM device specified, using"
$ main.c: line 131
$ MD5 ("no mixer device specified, using") = b0f42b65a1bf51303dde3f25b3a363bf
131 "no mixer device specified, using"
$ main.c: line 162
$ MD5 ("USB Radio Control utility,") = 879cb79ea281f0e716a65c3d6539427b
162 "USB Radio Control utility,"
$ main.c: line 163
$ MD5 ("version") = 5528902f5bba56c686370cd5d6a1399e
163 "version"
$ main.c: line 164
$ MD5 ("Type `?' for command list") = 5b1c7de165d75c73f1a9e74c47ad2533
164 "Type `?' for command list"
$set 4 OPEN_DEVICE_C_SET
$ open_device.c: line 45
$ MD5 ("impossible to open device") = 34b532b1bdc615e356532793950bb6d2
45 "impossible to open device"
$set 5 PARSE_C_SET
$ parse.c: line 70
$ MD5 ("ambiguous command") = 42f00559bc1d197ebaaa3ff1eacaadd4
70 "ambiguous command"
$ parse.c: line 78
$ MD5 ("invalid command, enter ``help'' for commands") = 1af6041e05ee178c5681702a8677f3d6
78 "invalid command, enter ``help'' for commands"
$set 6 RUN_C_SET
$ run.c: line 53
$ MD5 ("Radio device: ") = aae8fc591a5930dbd91d331112636dc2
53 "Radio device: "
$ run.c: line 83
$ MD5 ("Yes") = 9c2216de07acdf4cfa486c5a11b757a3
83 "Yes"
$ run.c: line 84
$ MD5 ("No") = f3cb8786bdccc588f18f5189e67ef675
84 "No"
$ run.c: line 86
$ MD5 ("no") = b71f46291e0353578289ed24b407e147
86 "no"
$ run.c: line 89
$ MD5 ("yes") = 3c1a9ba84a9dd5799c928b81fe37b90d
89 "yes"
$ run.c: line 96
$ MD5 ("locale: ") = 1cd86fbe95975c9be0471615fd628aa5
96 "locale: "
$ run.c: line 125
$ MD5 ("Mixer: ") = 1172145af3d673c6e3c319f572d45d4e
125 "Mixer: "
$ run.c: line 127
$ MD5 ("device: ") = 29ce9d6507a2cfbd36d161fa00ec3451
127 "device: "
$ run.c: line 167
$ MD5 ("Mixer device: ") = 24df969dbfec7829cf44bea8e0523027
167 "Mixer device: "
$ run.c: line 189
$ MD5 ("Invalid frequency") = 6a9f023a4a482e24e4b3753435db773e
189 "Invalid frequency"
$ run.c: line 196
$ MD5 ("command requires an argument") = d9e86923c5cd6cffe18d6719ed71b57b
196 "command requires an argument"
$ run.c: line 210
$ MD5 ("Not ") = ab09506901a4816b959d907c30a3aff8
210 "Not "
$ run.c: line 211
$ MD5 ("stereo") = 75cbd0454da3898f72b1e8bc8823e250
211 "stereo"
$ run.c: line 231
$ MD5 ("Yes") = 9c2216de07acdf4cfa486c5a11b757a3
231 "Yes"
$ run.c: line 232
$ MD5 ("No") = f3cb8786bdccc588f18f5189e67ef675
232 "No"
$ run.c: line 234
$ MD5 ("no") = b71f46291e0353578289ed24b407e147
234 "no"
$ run.c: line 237
$ MD5 ("yes") = 3c1a9ba84a9dd5799c928b81fe37b90d
237 "yes"
$ run.c: line 246
$ MD5 ("mute") = eb30b2aac17da4b94254d116aec14733
246 "mute"
$ run.c: line 250
$ MD5 ("invalid command arguments") = b4e7f169068298bd9eb36350652e2e63
250 "invalid command arguments"
$set 7 SET_DEVNAME_C_SET
$ set_devname.c: line 60
$ MD5 ("The device name exceeds") = 79d76c9a58fa9e515965dcf1c32168b3
60 "The device name exceeds"
$ set_devname.c: line 61
$ MD5 ("bytes") = 6d26be5f719f38f08647f2657a98fedb
61 "bytes"
$set 8 SET_LOCALE_C_SET
$ set_locale.c: line 67
$ MD5 ("impossible to open message catalog for locale ") = d4826d64d2123db5fc201e4969321215
67 "impossible to open message catalog for locale "
$ set_locale.c: line 73
$ MD5 ("The name exceeds") = c2ca69e8dad20b039ff3b033e4fa9a43
73 "The name exceeds"
$ set_locale.c: line 74
$ MD5 ("bytes") = 6d26be5f719f38f08647f2657a98fedb
74 "bytes"
$set 9 SET_VOLUME_C_SET
$ set_volume.c: line 92
$ MD5 ("impossible to execute command") = 550b29f33c41932e35afe2a5fa206504
92 "impossible to execute command"
$set 10 USAGE_C_SET
$ usage.c: line 45
$ MD5 ("usage: ufmcontrol") = 89123d616e631929abcf5ae0bb82c40f
45 "usage: ufmcontrol"
$ usage.c: line 46
$ MD5 ("[-hjsv] [-f device]") = 173b5990bda313d2fc418c536593b7bd
46 "[-hjsv] [-f device]"
$ usage.c: line 47
$ MD5 ("[-l locale] [-m mixer]") = dfeb570261ffd6f30073b0c9fec272bc
47 "[-l locale] [-m mixer]"
$ usage.c: line 48
$ MD5 ("[command ...]") = 70ab4ac52bdb9d3afd0021a284273c79
48 "[command ...]"
